language: node_js
install:
- nvm install node
- node -v
- cd api
- npm i -g yarn
- yarn
- npm install --save-dev jest
- npm install --save-dev @babel/plugin-transform-modules-commonjs
- npm i isomorphic-fetch
script:
- yarn test